terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error
